#!/bin/bash
cd "$(dirname "$0")/.." || exit 111

./script/setup || exit 111

# Run the tests
./script/test || exit 111

# Verify that no files were missing
has_changes=$(git diff)

if [[ ! -z "${has_changes}" ]]; then
  echo "ERROR: Running the tests caused unexpected changes in committed files."
  echo "Be sure to run ./script/test before pushing"
  git diff
  exit 1
fi
