name: Ci Tests
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: yarn
    - run: yarn test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        verbose: true