name: Ci Tests
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: yarn
    - name: Install dependencies
      run: yarn install --prefer-offline --frozen-lockfile
    - run: yarn test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        verbose: true